parameters:
#    mobile_ipermind.example.class: Mobile\IpermindBundle\Example

services:
#    mobile_ipermind.example:
#        class: %mobile_ipermind.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
